# Generated by Django 2.2.6 on 2019-12-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VKAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('vk_token', models.CharField(max_length=256)),
                ('vk_user_id', models.IntegerField(max_length=9)),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('access', models.CharField(max_length=128)),
                ('client_secret', models.CharField(max_length=256)),
            ],
        ),
    ]
