# Generated by Django 2.2.6 on 2019-12-02 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vkauth',
            old_name='client_secret',
            new_name='clientSecret',
        ),
        migrations.RenameField(
            model_name='vkauth',
            old_name='vk_token',
            new_name='vkToken',
        ),
        migrations.RenameField(
            model_name='vkauth',
            old_name='vk_user_id',
            new_name='vkUserId',
        ),
    ]
